# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_angency_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='angency_admin',
            new_name='agency_admin',
        ),
    ]
