# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170203_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profiles',
            field=models.ManyToManyField(through='accounts.Membership', to='users.Profile'),
        ),
    ]
