# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170203_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='profile',
        ),
    ]
