# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170203_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='office 1', max_length=100),
            preserve_default=False,
        ),
    ]
