# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170215_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile'),
        ),
    ]
