"""
Django settings for dwn project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import django.conf.global_settings as DEFAULT_SETTINGS
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.realpath(__file__))

IS_PRODUCTION = os.environ.get('PRODUCTION_SERVER', False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ce&@w*$-nj0nsh0a3(j*w3$et_5=r=b075l6xceis_p$aso8u2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if IS_PRODUCTION else True

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_WHITELIST = (
    'localhost:8080',
    'callsumo.ngrok.io',
    '45.55.200.192',
    'dg.callsumo.com'

)
CORS_ALLOW_CREDENTIALS = True

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'utils.paginators.CTMPagination',
    'PAGE_SIZE': 10
}


# AUTH BACKEND
AUTHENTICATION_BACKENDS = DEFAULT_SETTINGS.AUTHENTICATION_BACKENDS + [
    'authentication.backends.EmailAuthBackend',
]
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_extensions',
    'rest_framework_docs',
    'easy_pdf'
]

LOCAL_APPS = [
    'authentication',
    'accounts',
    'users',
    'calls',
    'utils',
    'reports'
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dwn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dwn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


# Callsumo legacy DB
callsumo_legacy_db = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'autoreporting',
    'USER': 'django_devops',
    'PASSWORD': 'mrsft123',
    'HOST': '52.40.168.99',
    'PORT': '3306'
}

#  If isn't production, use sqlite3, otherwhise use postgresql
if not IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        },
        'local_callsumo': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'autoreporting',
            'USER': 'root',
            # 'PASSWORD': 'mrsft123',
            'HOST': 'localhost',
            'PORT': '3306'
        },
        'callsumo_legacy': callsumo_legacy_db,
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'dwn',
            'USER': 'dwn',
            'HOST': 'db',
            'PASSWORD': 'dwn',
            'PORT': 5432,
        },
        'callsumo_legacy': callsumo_legacy_db
    }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_DIR, "static")
# STATIC_ROOT = 'static'

# EMAIL BACKEND
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# SMTP SETTINGS
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'levi@mrsft.com'
EMAIL_HOST_PASSWORD = 'Gramosa2405.'
EMAIL_PORT = 587


# CTM AUTH
CTM_TOKEN = "097a539eb55a80027731ba7f5b87acba"
CTM_SECRET = "1355c2a77dce366ab4dd6c6e5b7ec900c732"
CALLSUMO_HOST = "https://my.callsumo.com"
CTM_HOST = "https://api.calltrackingmetrics.com"
CTM_API_V = "/api/v1"

# JOTFORM AUTH
JOTFORM_API_KEY = "6a2bf80944c3095e2a8a79dc1ad7ba08"
JOTFORM_HOST = "https://api.jotform.com/"

# FRONTEND URL
FRONTEND_URL = 'http://localhost:8080'